### ISSUE TITLE
ATCA sensitivity calculator fails for 3mm frequency

### ISSUE THREAD

**Issue by ste616** [ste616/atca#15]
While trying to calculate run time of the calculator under different conditions, I got the following error:

```
$ time python ./atsenscalc_commandline.py -b CFB64M -s 16 -y 16 -W 14 -f 94000 -z 93900
MESSAGE: Starting calculator.
MESSAGE: Generating template spectra...
Traceback (most recent call last):
  File "./atsenscalc_commandline.py", line 122, in <module>
    sens.main(args)
  File "/home/jstevens/usr/src/atca/atsenscalc/code/atsenscalc_main.py", line 333, in main
    sens.templateFill(cacheTsys, workArea['continuum'])
  File "/home/jstevens/usr/src/atca/atsenscalc/code/atsenscalc_routines.py", line 430, in templateFill
    while (destTemplate['count'][i] == 0):
IndexError: index out of bounds
```

**Comment by ste616** [comment]
I should note that the exact same inputs work fine for `-f 5500 -z 5400`

**Comment by ste616** [comment]
Fix was made by checking for out-of-bound errors when doing the interpolation of system temperatures. Tested to work on local machine.
